### ISSUE TITLE
option to disable luajit in Configure script has no effect

### ISSUE THREAD

**Issue by mogui** [carlosabalde/libvmod-cfg#26]
using `--disable-luajit` in configure script fails:
`configure: error: Lua not found. Try --enable-luajit`

I know it is a dependancy, but i think the module is super useful also without lua features, maybe could be working anyway?

**Comment by carlosabalde** [comment]
Yes, `--disable-luajit` forces the VMOD to use vanilla Lua instead of LuaJIT. In any case, Lua / LuaJIT is a needed now due to requirements coming from some places where the VMOD is being used. It's not worth adding extra stuff for conditionally remove the Lua features on compilation time. Simply install Lua / LuaJIT and forget about Lua features if they are not useful for your use case. It's a simple library with almost not dependencies. It's should be simple and clean :)

**Comment by mogui** [comment]
yeah makes sense, i misunderstood the flag, I thought that it was meant to disable lua features not the jit :D sorry!

Great work btw
