### ISSUE TITLE
Question about Json file

### ISSUE THREAD

**Issue by redbox-cdn** [carlosabalde/libvmod-cfg#29]
it has several IDs  in json How do I get rule name for test 1 in this case?

```
{
  "data": [
    {
      "id": "test1",
      "attributes": {
        "rule_name": "testrule1"
      }
    },
    {
      "id": "test2",
      "attributes": {
        "rule_name": "testrule2"
      }
    }
  ]
}
```

when cfg format setting is INI,no problem at all.

```
[test1]
rule_name: test1

[test2]
rule_name: test2
```

I found myself it supported json and lua. Awesome!!!

**Comment by carlosabalde** [comment]
JSON is much more flexible than INI, but current JSON support in the VMOD is very basic. I've considered adding support for JSONPath in the past, but it was never implemented. Not sure if that will happen in the near future, but for sure not immediately because my holidays start right now (funny coincidence: I'll be traveling around Japan for the next three weeks) 🎉 

Btw, in addition to Lua scripts, support for JavaScript was also added recently to the VMOD (although Lua execution usually performs better).

**Comment by redbox-cdn** [comment]
Thank you for comment and enjoy holidays !!!
