### ISSUE TITLE
dlerror: /usr/lib64/varnish/vmods/libvmod_cfg.so: undefined symbol: mallctl

### ISSUE THREAD

**Issue by peppe5** [carlosabalde/libvmod-cfg#35]
Hi all, 
after updating varnish from version 6.0.11 to 6.0.13 I encounter the following error:
----> dlerror: /usr/lib64/varnish/vmods/libvmod_cfg.so: undefined symbol: mallctl <----

with varnish version 6.0.11 I was using this version libvmod-cfg-6.0-5.5 , I tried to change it using the latest available version 6 (libvmod-cfg-6.0-5.10) but I keep getting the same error

**Comment by carlosabalde** [comment]
Hi @peppe5,

Varnish Cache uses jemalloc as its default memory allocator. The undefined symbol you are referring to, `mallctl()`, is a function provided by the jemalloc library to control various aspects of the memory allocator. That function is used by the cfg VMOD in a couple of places in order to minimize the amount of memory used by jemalloc in its local thread cache, which is specially relevant when using the scripting features provided by the VMOD.

Unless there is something unusual in your setup, installing the jemalloc library should be enough to solve the issue. I'd expect that to be already installed in your system because of Varnish, but that should be the first thing to check. Alternatively, you can disable the jemalloc integration in the VMOD using the `--disable-flush-jemalloc-tcache` flag when running the `configure` script.

I hope this helps.

**Comment by peppe5** [comment]
Hi @carlosabalde,
using `./configure --disable-luajit --disable-flush-jemalloc-tcache` varnish is back to working! 
in the old version of varnish (6.0.11) I did not need to disable it.

Thank you very much for your precious help!
